site_name: My Docs
theme:
 name: 'material'
#theme:
#    name: dracula
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences